[[context]]
line = 5
content = """
// âœ‹âœ‹âœ‹âœ‹
// this is the main function ğŸƒ
func main() {
\ttime.Parse("asdf", "")
}
"""

[[result]]
line = 8
column = 12
rule_id = "errcheck"
message = "Error return value of `time.Parse` is not checked"
